addons:
  apt:
    packages:
    - libwxgtk2.8-dev
    
language: cpp

compiler:  
    - gcc

before_script:  
    - cd ~
    - cd timhutton/latticegas
    - mkdir build
    - cd build
    - cmake ..

script: make 
