sudo: required
dist: trusty

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.7
          packages:
            - libwxgtk2.8-dev
            - clang-3.7
      env: COMPILER=clang++-3.7
    - compiler: gcc
      addons:
        apt:
          packages:
            - libwxgtk2.8-dev
      env: COMPILER=g++
    
language: cpp

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make 
