sudo: required
dist: precise

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - libwxgtk2.8-dev
            - clang-3.8
      env: COMPILER=clang++-3.8
    - compiler: gcc
      addons:
        apt:
          packages:
            - libwxgtk2.8-dev
      env: COMPILER=g++
    
language: cpp

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make 
